<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tips</name>
   <tag></tag>
   <elementGuidId>c071948f-884e-443f-bb1a-f22bdbe79125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='sg-category-list-item'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tips&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4cdefdf-b4c6-43c8-904d-01ff3984c145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex w-full items-center justify-between rounded-md px-3 py-2 text-left text-sm font-bold transition-colors hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-200 text-gray-700</value>
      <webElementGuid>27c57a40-e0dd-4847-b985-13cb11ab7186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sg-category-list-item</value>
      <webElementGuid>b28f3c68-e4fa-4d5d-b617-43f3d559dada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tips</value>
      <webElementGuid>a2dcfe1a-5118-4ae2-be2f-92d9b78a7b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sg-categories-container&quot;)/div[@class=&quot;space-y-1&quot;]/div[@class=&quot;space-y-1&quot;]/div[@class=&quot;ml-4 space-y-1 border-l border-gray-200 pl-4&quot;]/div[@class=&quot;space-y-1&quot;]/div[@class=&quot;space-y-1&quot;]/button[@id=&quot;sg-category-list-item&quot;]</value>
      <webElementGuid>39b7d46f-cd4c-4305-9239-6abc961a2313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Asaya/Page_Blogs  Buy Beauty  Skincare Products O_9ccc91/iframe_Press_shopifyiframe</value>
      <webElementGuid>2a711fcb-4df8-4ef1-a43f-b4d37c2f9d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='sg-category-list-item'])[5]</value>
      <webElementGuid>1b357605-df03-40e6-b8b5-37133a367bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sg-categories-container']/div/div/div/div/div[4]/button</value>
      <webElementGuid>1982b11a-ed4e-4ccd-aa8b-edbca56d55a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Melanin Content'])[2]/following::button[1]</value>
      <webElementGuid>e1afa4f4-58e2-40f3-b277-eaa2ccca0be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingredient info'])[1]/following::button[2]</value>
      <webElementGuid>1f52055e-5b02-4ab1-a2a4-26295367ce5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured Collections'])[1]/preceding::button[1]</value>
      <webElementGuid>63ad719a-c598-4168-b8a3-d9c947313347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>2b371301-0b0b-4bbc-9f7a-48f7893b1b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sg-category-list-item' and (text() = 'Tips' or . = 'Tips')]</value>
      <webElementGuid>7d025aca-76a6-4773-b69e-9b1981dfcd94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
