<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skincare</name>
   <tag></tag>
   <elementGuidId>4138d628-8099-4a12-851f-02c4b78d9b32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sg-category-list-item']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sg-category-list-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Skincare&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9e377ec-a73b-404e-bb59-3959ebba49bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex w-full items-center justify-between rounded-md px-3 py-2 text-left text-sm font-bold transition-colors hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-200 bg-gray-100 text-gray-900</value>
      <webElementGuid>f1b6463b-68a2-4434-b072-7029b3f2449c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sg-category-list-item</value>
      <webElementGuid>b1d4444e-aa48-43c3-a56f-05b77aea0b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skincare</value>
      <webElementGuid>233a3fab-cf4b-46a8-a77d-d83e835a8a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sg-categories-container&quot;)/div[@class=&quot;space-y-1&quot;]/div[@class=&quot;space-y-1&quot;]/button[@id=&quot;sg-category-list-item&quot;]</value>
      <webElementGuid>9a985422-b7c0-488d-acc4-59725e4b9a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Asaya/Page_Blogs  Buy Beauty  Skincare Products O_9ccc91/iframe_Press_shopifyiframe</value>
      <webElementGuid>cd309ab8-90bd-4352-9302-4c17907e5e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sg-category-list-item']</value>
      <webElementGuid>f894fa22-f850-46b9-a32b-f27db4ce7bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sg-categories-container']/div/div/button</value>
      <webElementGuid>81787ba5-8099-4985-a20f-0c9bd592dcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORIES'])[1]/following::button[1]</value>
      <webElementGuid>917b366f-8d6e-4c44-b6c1-81f95a80b03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Melanin Content'])[1]/following::button[3]</value>
      <webElementGuid>821fd6cd-3023-450e-8b6d-d5969633b91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Common Questions'])[1]/preceding::button[1]</value>
      <webElementGuid>8b461f07-5377-4196-9275-03bbe9173d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>7291cfa5-752c-418c-b6e6-4eb1bd35194e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sg-category-list-item' and (text() = 'Skincare' or . = 'Skincare')]</value>
      <webElementGuid>55933472-0963-4ad1-aab4-0e07187ef6cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
