<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Press_shopifyiframe</name>
   <tag></tag>
   <elementGuidId>9e9ad404-21a8-40bd-9031-542a38de69fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='shopifyiframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shopifyiframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#shopifyiframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>47a240d3-6f9b-4ba2-a6ec-c35910e3f7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shopifyiframe</value>
      <webElementGuid>4b491247-cf6c-4aca-93be-123001bce337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://asayaprod-prodin.sangria.tech/blogs</value>
      <webElementGuid>03e7ec0d-c830-4a5f-ba96-5af0a3a95e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>6e179e2c-94a8-4bc3-bd23-42fbcb76e641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopifyiframe&quot;)</value>
      <webElementGuid>4fd88513-9161-45a9-889c-b038bbc816c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='shopifyiframe']</value>
      <webElementGuid>5cc47ed9-c0c4-4e0f-8413-f30b9a1aa355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='MainContent']/div/iframe</value>
      <webElementGuid>5be36027-456c-4841-952b-78380d977e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7fe36c38-4d06-4d72-b1de-eeea832e5a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'shopifyiframe' and @src = 'https://asayaprod-prodin.sangria.tech/blogs']</value>
      <webElementGuid>0db0afaa-1f41-41ba-bc38-226c1803916a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
