<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Skincare</name>
   <tag></tag>
   <elementGuidId>6f0dd117-9fe2-4a8f-9f47-aae11d28a0e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sg-category-list-item']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sg-category-list-item > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Skincare&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>28dbb32c-4f38-412c-ad87-8e53f95996a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skincare</value>
      <webElementGuid>73e78f72-526b-4b75-b3f2-4e338dc7380b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sg-category-list-item&quot;)/span[1]</value>
      <webElementGuid>2f744313-e960-4c2d-a014-860e755c360e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Asaya/Page_Blogs  Buy Beauty  Skincare Products O_9ccc91/iframe_Press_shopifyiframe</value>
      <webElementGuid>420abc6c-6b15-4a24-a982-b4079353adc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='sg-category-list-item']/span</value>
      <webElementGuid>68694d6f-6688-47a6-a149-efba3f93d35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORIES'])[1]/following::span[1]</value>
      <webElementGuid>273b658d-37c8-40ba-89bb-a036e45f037a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Melanin Content'])[1]/following::span[1]</value>
      <webElementGuid>ccb25858-0fd7-426d-bec6-b95c7b9db380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured Collections'])[1]/preceding::span[1]</value>
      <webElementGuid>02bc1720-7261-4b45-b48f-124aa2b67f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LATEST BLOGS'])[1]/preceding::span[2]</value>
      <webElementGuid>677c74ac-15fd-4fa2-bb21-e017cf6a9260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Skincare']/parent::*</value>
      <webElementGuid>51d7b24b-7554-4f9f-b806-c115606714c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>5a9d294b-99f2-4b80-bb7f-3c01f06347da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Skincare' or . = 'Skincare')]</value>
      <webElementGuid>a662e862-f71b-425f-bbb4-44aefabfc78c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
